name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Build com o utilitario dotnet
      run: dotnet build ${{ secrets.CAMINHO_PROJETO }} --configuration Release

    - name: Publish com o utilitario dotnet
      run: dotnet publish ${{ secrets.CAMINHO_PROJETO }} -c Release -o app
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
        
    - name: Copiando Deploy
      run: cp -fR ${{secrets.CAMINHO_DEPLOY}} ${{secrets.CAMINHO_APLICACAO}}
